/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class", 
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#241a00", 
        "surface-bright": "#fcf9f2", 
        "on-surface": "#1c1c18", 
        "on-tertiary-container": "#47471a", 
        "surface-container-high": "#ebe8e1", 
        "secondary": "#745b00", 
        "on-primary-container": "#554300", 
        "surface-tint": "#735c00", 
        "champagne-light": "#F9F295", 
        "on-tertiary-fixed": "#1d1d00", 
        "surface-container-low": "#f6f3ec", 
        "tertiary-fixed-dim": "#cbc990", 
        "on-secondary": "#ffffff", 
        "on-surface-variant": "#4d4635", 
        "on-secondary-fixed": "#241a00", 
        "secondary-fixed": "#ffe08b", 
        "on-tertiary": "#ffffff", 
        "surface-dim": "#dcdad3", 
        "secondary-container": "#fed65e", 
        "error-container": "#ffdad6", 
        "primary-container": "#d4af37", 
        "surface-container": "#f0eee7", 
        "on-primary": "#ffffff", 
        "on-error": "#ffffff", 
        "on-error-container": "#93000a", 
        "background": "#fcf9f2", 
        "tertiary-container": "#b7b67e", 
        "tertiary-fixed": "#e7e6a9", 
        "surface-container-lowest": "#ffffff", 
        "on-secondary-container": "#755c00", 
        "on-tertiary-fixed-variant": "#49491c", 
        "tertiary": "#616131", 
        "primary-fixed": "#ffe088", 
        "on-secondary-fixed-variant": "#584400", 
        "inverse-primary": "#e9c349", 
        "secondary-fixed-dim": "#e9c24d", 
        "error": "#ba1a1a", 
        "outline": "#7f7663", 
        "on-background": "#1c1c18", 
        "gold-gradient-start": "#D4AF37", 
        "error-rose": "#C62828", 
        "inverse-surface": "#31312c", 
        "success-emerald": "#2E7D32", 
        "gold-gradient-end": "#C5A028", 
        "primary-fixed-dim": "#e9c349", 
        "on-primary-fixed-variant": "#574500", 
        "inverse-on-surface": "#f3f0ea", 
        "surface-variant": "#e5e2db", 
        "surface": "#fcf9f2", 
        "slate-text": "#2D2D2D", 
        "primary": "#735c00", 
        "outline-variant": "#d0c5af", 
        "surface-container-highest": "#e5e2db"
      }, 
      borderRadius: {
        DEFAULT: "0.25rem", 
        lg: "0.5rem", 
        xl: "0.75rem", 
        full: "9999px"
      }, 
      spacing: {
        "container-max": "1200px", 
        "margin-mobile": "16px", 
        "margin-desktop": "40px", 
        "section-gap": "80px", 
        "gutter": "24px", 
        "component-gap": "24px"
      }, 
      fontFamily: {
        "body-lg": ["var(--font-inter)", "sans-serif"], 
        "body-md": ["var(--font-inter)", "sans-serif"], 
        "display-lg": ["var(--font-playfair)", "serif"], 
        "headline-md": ["var(--font-playfair)", "serif"], 
        "price-display": ["var(--font-playfair)", "serif"], 
        "display-lg-mobile": ["var(--font-playfair)", "serif"], 
        "headline-sm": ["var(--font-playfair)", "serif"], 
        "label-md": ["var(--font-inter)", "sans-serif"], 
        "headline": ["var(--font-playfair)", "serif"], 
        "display": ["var(--font-playfair)", "serif"], 
        "body": ["var(--font-inter)", "sans-serif"], 
        "label": ["var(--font-inter)", "sans-serif"]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
